[Appearance]
color_scheme_path=
icon_theme=Papirus-Dark
style=kvantum

[StyleSheet]
stylesheets=/home/jason/.config/qt6ct/qss/material-darker.qss

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x1\x85\0\0\x2\xa8\0\0\0\0\0\0\0\0\0\0\x1\x85\0\0\x2\xa8\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x1\x85\0\0\x2\xa8)
