add_newline = true
format = """
[░▒▓](#6D85D9)\
[  ](bg:#6D85D9 fg:#000000)\
$directory\
[](fg:#6D85D9 bg:#48547E)\
$git_branch\
[](fg:#48547E bg:#353B50)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#353B50)\
$fill\
[](fg:#353B50)\
$cmd_duration\
[](fg:#48547E bg:#353B50)\
$time\
\n$character"""

[fill]
symbol=" "

[cmd_duration]
min_time = 100
format = '[ $duration ](bold fg:#FFEAD6 bg:#353B50)'

[character]
success_symbol = "[░▒▓ ](#6D85D9)"
error_symbol = "[░▒▓ ](#FD0000)"
vimcmd_symbol = "[](green)"

[directory]
style = "fg:#000000 bg:#6D85D9 bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#48547E"
format = '[[ $symbol $branch ](fg:#EEEEEE bg:#48547E)]($style)'

[git_status]
style = "bg:#48547E"
format = '[[($all_status$ahead_behind )](fg:#EEEEEE bg:#48547E)]($style)'

[nodejs]
symbol = ""
style = "bg:#353B50"
format = '[[ $symbol ($version) ](fg:#DDDDDD bg:#353B50)]($style)'

[rust]
symbol = ""
style = "bg:#353B50"
format = '[[ $symbol ($version) ](fg:#DDDDDD bg:#353B50)]($style)'

[golang]
symbol = ""
style = "bg:#353B50"
format = '[[ $symbol ($version) ](fg:#DDDDDD bg:#353B50)]($style)'

[php]
symbol = ""
style = "bg:#353B50"
format = '[[ $symbol ($version) ](fg:#DDDDDD bg:#353B50)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#240D05"
format = '[[  $time ](fg:#FFEAD6 bg:#48547E)]($style)'

