#!/bin/bash
# A simple sketchybar config for aerospace users to get started with
# Not too different from the base starting config!
PLUGIN_DIR="$CONFIG_DIR/plugins"
source "$PLUGIN_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=32 color="$TRANSPARENT" padding_left=6 padding_right=6

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
    padding_left=0
    padding_right=0
    icon.font="Hack Nerd Font:Bold:16.0"
    label.font="Hack Nerd Font:Regular:16.0"
    icon.color="$TEXT_GREY"
    label.color="$TEXT_WHITE"
    icon.padding_left=4
    icon.padding_right=4
    label.padding_left=4
    label.padding_right=4
    updates=on
    y_offset=-2
)
sketchybar --default "${default[@]}"

###### Apple Logo #####
#sketchybar --add item apple_logo left \
#    --set apple_logo \
#    icon="" \
#    icon.font="Hack Nerd Font:Bold:20.0" \
#    icon.color="$TEXT_WHITE" \
#    icon.padding_left=10 \
#    icon.padding_right=0 \
#    background.color="$TRANSPARENT" \
#    background.corner_radius=16 \
#    background.height=26 \
#    background.padding_left=0 \
#    background.padding_right=0 \
#    padding_left=0 \
#    padding_right=0

##### Adding aerospace layouts #####
# Add the aerospace events we specified in aerospace.toml
sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_monitor_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --set space.$sid \
        display="$(
            v=$(aerospace list-windows --workspace "$sid" --format "%{monitor-appkit-nsscreen-screens-id}" | cut -c1)
            echo "${v:-1}"
        )" \
        drawing=off \
        background.corner_radius=15 \
        background.drawing=on \
        background.border_width=1 \
        background.border_color="$BORDER_DARK" \
        background.height=23 \
        background.padding_right=5 \
        background.padding_left=0 \
        background.color="$BACKGROUND_LIGHT" \
        icon="$sid" \
        icon.shadow.drawing=off \
        icon.padding_left=10 \
        icon.padding_right=-2 \
        padding_left=2 \
        label.font="sketchybar-app-font:Regular:16.0" \
        label.padding_right=20 \
        label.padding_left=3 \
        label.y_offset=-1 \
        label.shadow.drawing=off \
        click_script="aerospace workspace $sid"
done

# Load Icons on startup
for mid in $(aerospace list-monitors | cut -c1); do
    for sid in $(aerospace list-workspaces --monitor $mid --empty no); do
        apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

        sketchybar --set space.$sid drawing=on

        icon_strip=" "
        if [ "${apps}" != "" ]; then
            while read -r app; do
                icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
            done <<<"${apps}"
        else
            icon_strip=""
        fi
        sketchybar --set space.$sid label="$icon_strip"
    done
done

# Set color for currently focused space
sketchybar --set space."$(aerospace list-workspaces --focused)" background.color=$BACKGROUND_SELECTED label.color=$TEXT_WHITE icon.color=$TEXT_WHITE background.border_color=$TEXT_WHITE

# Subscribe to aerospace events to update workspace icons
sketchybar --add item space_separator left \
    --set space_separator \
    icon.drawing=off \
    label.drawing=off \
    background.drawing=off \
    width=0 \
    script="$PLUGIN_DIR/space_windows.sh" \
    --subscribe space_separator aerospace_workspace_change front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other gititems respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
    --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
    icon=" " \
    icon.color="$TEXT_WHITE" \
    icon.padding_left=8 \
    icon.y_offset=0 \
    label.color="$TEXT_WHITE" \
    label.y_offset=-1 \
    label.font="alarm clock:Regular:18.0" \
    label.padding_right=10 \
    padding_right=0 \
    padding_left=5 \
    --add item volume right \
    --set volume script="$PLUGIN_DIR/volume.sh" \
    padding_left=5 \
    padding_right=5 \
    --subscribe volume volume_change \
    \
    --add item battery right \
    --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
    --subscribe battery system_woke power_source_change \
    \
    --add item wifi right \
    --set wifi script="$PLUGIN_DIR/wifi.sh" label.font="SF Pro:Italic:12.0" label.y_offset=-3 \
    label.padding_right=0 \
    label.padding_left=0 \
    padding_left=5 \
    popup.background.color="$BACKGROUND_DARK" \
    popup.background.border_width=2 \
    popup.background.border_color="$TEXT_GREY" \
    popup.background.corner_radius=10 \
    popup.y_offset=5 \
    label.max_chars=8 \
    scroll_texts=true \
    --subscribe wifi wifi_change mouse.entered mouse.exited \
    \
    --add item wifi.priv.addr popup.wifi \
    --set wifi.priv.addr icon="󰌗" \
    \
    --add item wifi.pub.addr popup.wifi \
    --set wifi.pub.addr icon="󰖟" \
    --add item swap e \
    --set swap update_freq=1 script="$PLUGIN_DIR/memswap.sh" \
    icon="" \
    background.corner_radius=16 \
    background.color="$BACKGROUND_DARKER" \
    background.height=26 \
    label.font="Hack Nerd Font:Italic:14.0" \
    icon.padding_left=8 \
    label.padding_right=8 \
    click_script="open -a 'Activity Monitor'" \
    background.border_width=1 \
    background.border_color=$BORDER_DARK \
    \
    --add item cpu e \
    --set cpu update_freq=1 script="$PLUGIN_DIR/cpu.sh" \
    icon="" \
    background.corner_radius=16 \
    background.color="$BACKGROUND_DARKER" \
    background.height=26 \
    label.font="Hack Nerd Font:Italic:14.0" \
    icon.padding_left=8 \
    label.padding_right=8 \
    padding_left=5 \
    click_script="open -a 'Activity Monitor'" \
    background.border_width=1 \
    background.border_color=$BORDER_DARK
    \
    --add item ncspot e \
    --set ncspot updates=when_shown update_freq=2 script="$PLUGIN_DIR/ncspot.sh" \
    icon="" \
    background.corner_radius=16 \
    background.color="$BACKGROUND_DARKER" \
    background.height=26 \
    label.font="Hack Nerd Font:Bold:14.0" \
    label.color="$TEXT_WHITE" \
    label.max_chars=15 \
    scroll_texts=true \
    click_script="tmux send-keys -t spot 'P'" \
    \
    --add item day e \
    --set day label.max_chars=20 \
    icon.padding_left=2 \
    icon.padding_right=0 \
    icon.font="sketchybar-app-font:Regular:16.0" \
    icon=":obsidian:" \
    label.padding_left=2 \
    label.padding_right=2 \
    background.corner_radius=16 \
    background.color="$BACKGROUND" \
    background.height=26 \
    label.font="Hack Nerd Font:Regular:14.0" \
    label.color="$TEXT_GREY" \
    scroll_texts=true \
    drawing=off

#### Groups !!! ####
sketchybar --add bracket spaces '/space\..*/' \
    --set spaces background.color="TRANSPARENT" \
    background.corner_radius=16 \
    background.height=26 \
    padding_left=0 \

sketchybar --add bracket rightItems volume battery wifi \
    --set rightItems background.color="$BACKGROUND_SELECTED" \
    background.corner_radius=16 \
    background.height=26 \
    background.border_width=1 \
    background.border_color=$BORDER_DARK

sketchybar --add bracket clock \
    --set clock background.color="$BACKGROUND_DARK" \
    background.corner_radius=16 \
    background.height=26 \
    padding_right=0 \
    background.border_width=1 \
    background.border_color=$BORDER_DARK

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
